version: '3.4'

services:
   test_db:
     restart: always
     image: postgres
     container_name: test_ntnui_db
     environment:
       NTNUI_SECRET_KEY: ${NTNUI_SECRET_KEY}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_HOST: test_db
       POSTGRES_PORT: 5433
     volumes:
       - postgres_data:/var/lib/postgresql/data
     ports:
      - "5433:5433"
     command: -p 5433
   backend:
     container_name: ntnui_backend
     command: python manage.py runserver 0.0.0.0:8000
     build:
       context: .
       dockerfile: config/django/Dockerfile
     volumes:
        - .:/code
     env_file:
       - .env
     depends_on:
       - test_db
     ports:
      - "8000:8000"
     environment:
       PRODUCTION: 'false'
       DJANGO_SETTINGS_MODULE: 'ntnui.settings.local'
volumes:
  postgres_data:
