name: Back end CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_using_docker_compose:
    env:
      NTNUI_SECRET_KEY: ${secrets.NTNUI_SECRET_KEY}
      POSTGRES_USER: ${secrets.POSTGRES_USER}
      POSTGRES_PASSWORD: ${secrets.POSTGRES_PASSWORD}
      POSTGRES_DB: ${secrets.POSTGRES_DB}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        docker-compose -f docker-compose.github.yml build
    - name: Run saftey check, formatting check and test suite
      run: |
        docker-compose -f docker-compose.github.yml up --abort-on-container-exit
