# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Front-end lint and test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install and build
        working-directory: ./frontend-koie-booking
        run: |
          npm install
          npm run build --if-present
      - name: Audit packages
        working-directory: ./frontend-koie-booking
        run: npm audit --audit-level=high
      - name: Lint
        working-directory: ./frontend-koie-booking
        run: npm run lint
      - name: Unit tests
        working-directory: ./frontend-koie-booking
        run: npm run test:unit
